### ISSUE TITLE
MTCI - reprocessamento Temas 

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#114]
Solicito reprocessar temas (clusters) da instância MTCI devido correção. Email com arquivos enviado nesta data
Obrigada

**Comment by renatomurasaki** [comment]
Rose,


Favor manter os arquivos associados ao issue dentro do issue. O github permite anexar arquivos dentro do próprio issue. Assim mantemos a rastreabilidade e melhor gestão da informação.


Obrigado.

________________________________
De: pintoros <notifications@github.com>
Enviado: sexta-feira, 23 de novembro de 2018 12:40:01
Para: bireme/db-processing
Cc: Subscribed
Assunto: [bireme/db-processing] MTCI - reprocessamento Temas (#114)


Solicito reprocessar temas (clusters) da instância MTCI devido correção. Email com arquivos enviado nesta data
Obrigada

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F114&data=02%7C01%7Cmurasaki%40paho.org%7C7121a66e5c6b4ce5d2a308d651518e9e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636785808059384895&sdata=SzVOi5DE91gJywgFt2NEpNImR02Xro60s5WUEaSGR2U%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16lmhCtT814vsh5CdUJbfD4Cx34zwks5uyAjBgaJpZM4Ywwmb&data=02%7C01%7Cmurasaki%40paho.org%7C7121a66e5c6b4ce5d2a308d651518e9e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636785808059384895&sdata=xJwItSsS65viCEfUWh0PtJ63A2CPywIAGkSzrj3Qo3o%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
processamento iniciado domingo, dia 15/11

**Comment by botturam** [comment]
Processamento regular disponível em produção.
