### ISSUE TITLE
Processamento da estratégia - Genero para vitrine do conhecimento

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#151]
Solicito processamento da estratégia de Genero, em txt anexo, para Vitrine do Conhecimento sobre o tema.
[Tema_Gender.txt](https://github.com/bireme/db-processing/files/3143492/Tema_Gender.txt)

**Comment by botturam** [comment]
Rose, deu certo. Há apenas um acerto a fazer na estratégia original:  "interes sexual" OR OR "desejo sexual"

**Comment by pintoros** [comment]
Vou ajustar Marcelo, muito obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e39045cf-9e1b-4485-b451-5a3b6e77c7e3]

________________________________
De: botturam <notifications@github.com>
Enviado: quarta-feira, 8 de maio de 2019 11:53
Para: bireme/db-processing
Cc: Pinto, Rosemeire (BIR); Author
Assunto: Re: [bireme/db-processing] Processamento da estratégia - Genero para vitrine do conhecimento (#151)


Rose, deu certo. Há apenas um acerto a fazer na estratégia original: "interes sexual" OR OR "desejo sexual"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F151%23issuecomment-490518976&data=02%7C01%7Cpintoros%40paho.org%7C906c5e91f7174eac248508d6d3c4ece1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636929240074059121&sdata=enJlyn%2BZ2F1Y3ryA7WjE72iFB1R79QAlJw5bcgc2Js8%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4EA6PGVXVMNO5NTSADPULSOLANCNFSM4HKW2IIQ&data=02%7C01%7Cpintoros%40paho.org%7C906c5e91f7174eac248508d6d3c4ece1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636929240074059121&sdata=tP1Q7k6Kp%2F7za9Hcp1hVYRzdO43o5bmtSIRmg9tCS5w%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Segue o anexo corrigido, o número de resultado ficou em torno de 101 mil registros.
[Tema_Gender.txt](https://github.com/bireme/db-processing/files/3158974/Tema_Gender.txt)

**Comment by botturam** [comment]
Rose,

a pesquisa para o tema prioritário "genero" está disponível para pesquisa no Portal Regional através da seguinte expressão:

tag_temasprioritarios:"genero"

Falta o processamento de MEDLINE_1966-2018, ainda em andamento, previsão para 6f ou 2f. Eu aviso quando terminar.

**Comment by botturam** [comment]
Disponível em produção.

**Comment by renatomurasaki** [comment]
Por favor, gerar os respectivos csv.


________________________________
De: botturam <notifications@github.com>
Enviado: sexta-feira, 31 de maio de 2019 10:28
Para: bireme/db-processing
Cc: Subscribed
Assunto: Re: [bireme/db-processing] Processamento da estratégia - Genero para vitrine do conhecimento (#151)


Disponível em produção.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F151%3Femail_source%3Dnotifications%26email_token%3DAAJLL2QYIOYNY2674MILGZLPYERWBA5CNFSM4HKW2II2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWVG3TA%23issuecomment-497708492&data=02%7C01%7Cmurasaki%40paho.org%7Ca8ce9ec4527f47dd00ab08d6e5cbcec3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636949060848090459&sdata=hYHLhEM1%2Bqvi%2BUNoNEx%2B1k2YE1ffz7gh32culbtrcm8%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJLL2RC6HIXWJSEBW5SXW3PYERWBANCNFSM4HKW2IIQ&data=02%7C01%7Cmurasaki%40paho.org%7Ca8ce9ec4527f47dd00ab08d6e5cbcec3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636949060848090459&sdata=u1yORFhwvS%2F912MfNjk8crqBdZ05kmBt7HlET9KZpzA%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
arquivos gerados e disponíveis em FTP e pen drive.

**Comment by botturam** [comment]
disponível em produção

**Comment by pintoros** [comment]
Estratégia Narrow para Gênero
[Gender_narrow.txt](https://github.com/bireme/db-processing/files/3941864/Gender_narrow.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível para pesquisa no Portal Regional:

tag_temasprioritarios:"genero"

**Comment by botturam** [comment]
disponível em produção.
