### ISSUE TITLE
Tradução das etiquetas do IAHx do cluster de Tipo de Estudos

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#312]
@pintoros

Devido ao processamento de novos elementos no cluster de "Tipo de Estudos" estão ficando disponibilizados elementos sem traduções.

Screening_studies
Policy_brief
Prevalence_studies
Incidence_studies
Overview
Sysrev_observational_studies

Gostaria de solicitar que fosse traduzido esses elementos para os 4 idiomas (português, inglês, Espanhol e Frances)

Obrigado,

**Comment by marcoslmori** [comment]
@pintoros 

Devido ao processamento de novos elementos no cluster de "Tipo de Estudos"  estão ficando disponibilizados elementos sem traduções. 

Screening_studies
Policy_brief
Prevalence_studies
Incidence_studies
Overview
Sysrev_observational_studies

Gostaria de solicitar que fosse traduzido esses elementos para os 4 idiomas (português, inglês, Espanhol e Frances)

Obrigado,

**Comment by botturam** [comment]
**Atualmente temos:**

case_control="Estudo de casos e controles"
cohort="Estudo de coorte"
clinical_trials="Ensaio clínico controlado"
case_reports="Relato de casos"
guideline="Guia de prática clínica"
overview="Overview"
systematic_reviews="Revisão sistemática"
health_technology_assessment="Avaliação de tecnologias de saúde"
health_economic_evaluation="Avaliação econômica em saúde"
evidence_synthesis="Síntese de evidências"
incidence="Estudo de incidência"
prevalence="Estudo de prevalência"

**faltam** (revisar os labels abaixo):

broad_synthesis
evaluation_studies
evidence_synthesis
implementation_research
incidence_studies
policy_brief
prevalence_studies
primary_study
screening_studies
structured_summary_of_systematic_review
sysrev_observational_studies

**Comment by pintoros** [comment]
[tradução-labels-police-makers.xlsx](https://github.com/bireme/db-processing/files/4880619/traducao-labels-police-makers.xlsx)

* O tipo primary_study não deve aparecer nos clusters. 

* policy_brief e evidence_synthesis são o mesmo tipo, manter para processamento somente a estratégia  policy_brief 

* O tipo structured_summary_of_systematic_review ainda não é considerado no cluster tipo de estudos.

**Comment by botturam** [comment]
Terei que refazer o MEDLINE inteiro (2 semanas).

Mori, é possível retirar a entrada "primary_study" do cluster Tipo de Estudo?

**Comment by pintoros** [comment]
Sem problemas Marcelo, estamos ajustando, é só não incluir no próximo.




Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:370cbfdd-e03f-4a98-bbba-8712ac2318f5]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 6 de julho de 2020 16:16
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Assign <assign@noreply.github.com>
Assunto: Re: [bireme/db-processing] Tradução das etiquetas do IAHx do cluster de Tipo de Estudos (#312)


Terei que refazer o MEDLINE inteiro (2 semanas).

Mori, é possível retirar a entrada "primary_study" do cluster Tipo de Estudo?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F312%23issuecomment-654418057&data=02%7C01%7Cpintoros%40paho.org%7Cdbe2157bd0c34817dc9208d821e12371%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637296598142469988&sdata=rpmTIta8tthLChTYVZmWUwixVIFS17v88bplHC1UowE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CUVT4GEMLAAWDXDSDR2IPKHANCNFSM4OHBB26A&data=02%7C01%7Cpintoros%40paho.org%7Cdbe2157bd0c34817dc9208d821e12371%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637296598142469988&sdata=wIHEkk%2FyiVRxkqgOI7%2FH9jscZJUdQEcAKMoWBEdG%2B%2Fo%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
apenas para registrar:

1) retirei "primary_study" do processamento (epistemonikos)
2) retirei também as antigas estratégias IAH de "evidence_synthesis" (LILACS e MEDLINE)
3) "structured_summary_of_systematic_review" - disponível em produção (1.842 docs) - falta criar o label para o Mori.

**Comment by pintoros** [comment]
Segue a tradução do label para structured_summary_of_systematic_review 

Structured summary of systematic review / Resumo estruturado de revisão sistemática / Resumen estructurado de revisión sistemática / Résumé structuré de revue systematique

Segue abaixo o anexo atualizado com todos os filtros de estudo e clusters relacionados

[tradução-labels-police-makers.xlsx](https://github.com/bireme/db-processing/files/4899330/traducao-labels-police-makers.xlsx)

**Comment by pintoros** [comment]
Segue o arquivo atualizado com a tradução labels para Tipos de Estudo, Aspectos e temas da interface police_makers
[tradução-labels-police-makers.xlsx](https://github.com/bireme/db-processing/files/5105481/traducao-labels-police-makers.xlsx)

**Comment by marcoslmori** [comment]
[Traducao-labels-police-makers_atualizado_11092020.xlsx](https://github.com/bireme/db-processing/files/5232675/Traducao-labels-police-makers_atualizado_11092020.xlsx)
Novos ajustes de tradução solicitados pela Rosemeire

**Comment by renatomurasaki** [comment]
@marcoslmori foram realizados esses ajustes?

**Comment by marcoslmori** [comment]
Sim, Renato, não tem nada pendente de tradução com a Rose
