### ISSUE TITLE
Estabelecer processamento de BDENF baseando-se apenas na coleta FI-Admin

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#323]
Foram coletados IDs marcados com BDENF a partir do FI-Admin.
Na sequência foi desativado o processo que concatenava base isis congelada mais registros oriundo de coleta ao Fi-Admin.

**Comment by renatomurasaki** [comment]
@falbrito quantos registros foram recuperados? O @dossanluc estava fazendo o mesmo para o repositório de ETL e foram recuperados um pouco mais de 22 mil e a base completa parece ter mais de 40 mil.

**Comment by falbrito** [comment]
@renatomurasaki o número total de registros coletados hoje a partir do FI-Admin somam 43.115.

O conteúdo ainda está em fase de processamento e em breve estará em produção.

**Comment by renatomurasaki** [comment]
Obrigado @falbrito 

@dossanluc veja com o @falbrito o critério utilizado para que o ETL siga o mesmo e tenhamos a mesma quantidade, por favor

**Comment by dossanluc** [comment]
Boa tarde Renato,
O processo de carga já esta atualizado para carregar os novos dados conforme a base do FI-Admin.
O processo esta pronto para rodar hoje a noite.

Grato,
Luciano
________________________________
De: Renato Murasaki <notifications@github.com>
Enviado: quarta-feira, 15 de julho de 2020 16:47
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: dos Santos, Luciano (BIR) <dossanluc@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/db-processing] Estabelecer processamento de BDENF baseando-se apenas na coleta FI-Admin (#323)


Obrigado @falbrito<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalbrito&data=02%7C01%7Cdossanluc%40paho.org%7Ce3e124c6f83748d3c09708d828f7da38%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637304392263777530&sdata=f%2BXmyDALcFoiHrn%2FYzq6BKfBLjN3v3480MfJcKAvaT0%3D&reserved=0>

@dossanluc<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdossanluc&data=02%7C01%7Cdossanluc%40paho.org%7Ce3e124c6f83748d3c09708d828f7da38%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637304392263777530&sdata=c%2BOyZl4vWOGGqsXRTvh90qjVjtB%2FPGS%2BbD1JFssiF8g%3D&reserved=0> veja com o @falbrito<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalbrito&data=02%7C01%7Cdossanluc%40paho.org%7Ce3e124c6f83748d3c09708d828f7da38%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637304392263787529&sdata=NTrQZESf6L6ysKqm4Q6%2FRm5TUJeDIY78085W4BNHmZY%3D&reserved=0> o critério utilizado para que o ETL siga o mesmo e tenhamos a mesma quantidade, por favor

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F323%23issuecomment-658971315&data=02%7C01%7Cdossanluc%40paho.org%7Ce3e124c6f83748d3c09708d828f7da38%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637304392263787529&sdata=9UEfnXeUWmFt2lt2rR9bCLStib0euv%2BUbKFyjaUj7bw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL6TIO2ZHJW4ZQNUL5XGBFLR3YBTTANCNFSM4OZ3DKZQ&data=02%7C01%7Cdossanluc%40paho.org%7Ce3e124c6f83748d3c09708d828f7da38%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637304392263787529&sdata=GOHm%2F1OYLvi8PsmGtRsbPccm1tvAacApwoCZOO0Udsw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
disponível em produção.

**Comment by renatomurasaki** [comment]
Obrigado
