### ISSUE TITLE
Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#370]
[Impacto do trabalho na saúde do trabalhador da Enfermagem.txt](https://github.com/bireme/db-processing/files/5239120/Impacto.do.trabalho.na.saude.do.trabalhador.da.Enfermagem.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"

**Comment by pintoros** [comment]
Demora mais uns dias para Medline né Marcelo?
Em todo caso já fiz o link e enviei para o pessoal da BVS.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:ef130439-2c89-4b5c-a980-e4209e04bc64]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 11:25
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744474885&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460283684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uJj0VsdzBTnE5jwbUutE%2FBvFGdaUbKFhXBB7MwL0juA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HWCHRT4CLJYBSJH4LSUYN6RANCNFSM4RQMEUUA&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460293642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lYp4JGAMchDRN0ZJa4zlomwZ%2BwiRl6xx659mrzo5Y%2BU%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Rose,

O MEDLINE-Ano corrente (2020) creio que 4f; o MEDLINE66-19, 2 semanas. Na verdade eu nem ia fazer mais este ano, pois o MEDLINE2021 será liberado pela NLM esta semana.

abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: pintoros <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 12:34
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Bottura, Marcelo (BIR) <botturam@paho.org>; Comment <comment@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


Demora mais uns dias para Medline né Marcelo?
Em todo caso já fiz o link e enviei para o pessoal da BVS.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:ef130439-2c89-4b5c-a980-e4209e04bc64]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 11:25
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744474885&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460283684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uJj0VsdzBTnE5jwbUutE%2FBvFGdaUbKFhXBB7MwL0juA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HWCHRT4CLJYBSJH4LSUYN6RANCNFSM4RQMEUUA&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460293642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lYp4JGAMchDRN0ZJa4zlomwZ%2BwiRl6xx659mrzo5Y%2BU%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744520060&data=04%7C01%7Cbotturam%40paho.org%7Cea05e8a3b32c4fb5400f08d8a045c637%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435568821182820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BbPCQFW0V2UTMWeCz834kZLo0u9VUZLw0B3NuIoTEf8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEMRPF7SEGSSNAGVPNK2BT3SUYWBBANCNFSM4RQMEUUA&data=04%7C01%7Cbotturam%40paho.org%7Cea05e8a3b32c4fb5400f08d8a045c637%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435568821192781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Kzq9908eAOAOdTr0S%2BLXQOr%2BSFNXWr7w4niTriPXME%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
OK Marcelo, eu aviso o pessoal e vc processa no inicio do próximo ano então.

Abraço



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:b62416dc-96fb-4c80-863e-c3e1f87a23b1]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 14:04
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


Rose,

O MEDLINE-Ano corrente (2020) creio que 4f; o MEDLINE66-19, 2 semanas. Na verdade eu nem ia fazer mais este ano, pois o MEDLINE2021 será liberado pela NLM esta semana.

abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: pintoros <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 12:34
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Bottura, Marcelo (BIR) <botturam@paho.org>; Comment <comment@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


Demora mais uns dias para Medline né Marcelo?
Em todo caso já fiz o link e enviei para o pessoal da BVS.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:ef130439-2c89-4b5c-a980-e4209e04bc64]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 14 de dezembro de 2020 11:25
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Impacto do trabalho na saúde do trabalhador da Enfermagem (#370)


disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744474885&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460283684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uJj0VsdzBTnE5jwbUutE%2FBvFGdaUbKFhXBB7MwL0juA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HWCHRT4CLJYBSJH4LSUYN6RANCNFSM4RQMEUUA&data=04%7C01%7Cpintoros%40paho.org%7C40616cc712974d37ef4108d8a03c24a9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527460293642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lYp4JGAMchDRN0ZJa4zlomwZ%2BwiRl6xx659mrzo5Y%2BU%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744520060&data=04%7C01%7Cbotturam%40paho.org%7Cea05e8a3b32c4fb5400f08d8a045c637%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435568821182820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BbPCQFW0V2UTMWeCz834kZLo0u9VUZLw0B3NuIoTEf8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEMRPF7SEGSSNAGVPNK2BT3SUYWBBANCNFSM4RQMEUUA&data=04%7C01%7Cbotturam%40paho.org%7Cea05e8a3b32c4fb5400f08d8a045c637%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435568821192781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9Kzq9908eAOAOdTr0S%2BLXQOr%2BSFNXWr7w4niTriPXME%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F370%23issuecomment-744577729&data=04%7C01%7Cpintoros%40paho.org%7Ca35811c4a6784754ba6508d8a0525f19%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435622934887601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UjrGecbz50y2POkkYRpgZT%2FzCrQ2OtQWtjGK1dAbOKo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BAUNW6OVWS4LNFO4DSUZATHANCNFSM4RQMEUUA&data=04%7C01%7Cpintoros%40paho.org%7Ca35811c4a6784754ba6508d8a0525f19%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435622934897591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=voienPcXRJglaIb20sA9QTAZ1NBCWL4C%2Bjm02d23TAQ%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
