### ISSUE TITLE
Verificar processo de deduplicação WHO COVID-19 com parâmetros da Elsevier

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#376]
Caso de duplicação com aparente alto nível de similaridade:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-186589
https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-163410

**Comment by botturam** [comment]
este par de duplicados (v1 e v2) trata-se de um falso positivo, prejudicado pela baixa similaridade dos títulos (v9):

operacao@serverofi5:/bases/oai.pmh/xml.rec/bkp_Elsevier/Arquivo_Deduplicacao $ mx Potential_WHO_Duplicates_TAB "text=163410"
mfn=  1948
  **1  "163410"
  2  "186589"**
  3  "10.2196/19301"
  4  "10.2196/19301"
  5  "referencing the novel coronavirus as the chinese virus or china virus on twitter covid-19 stigma"
  6  "creating covid-19 stigma by referencing the novel coronavirus as the chinese virus on twitter quantitative analysis of social media data"
  7  "background stigma is the deleterious, structural force that devalues members of groups that hold undesirable characteristics. since, stigma is created and reinforced by society -- through in-person and online social interactions -- referencing the novel coronavirus as the chinese virus or china virus has the potential to create and perpetuate stigma. objective our objective was to assess if there was an increase in the frequency of the phrases chinese virus and china virus on twitter, post- the march 16, 2020 united states presidential reference of this term. methods using the sysomos software, we extracted tweets from the united states using a list of keywords that were derivatives of chinese virus. we compared tweets at the national and state levels posted between march 9th and march 15th pre-period with those posted between march 19th and march 25th post-period. we used stata 16 for quantitative analysis and python to plot a state-level heat map. results a total of 16,535 chinese virus or china virus tweets were identified in the pre-period and 177,327 of these tweets were identified in the post-period, illustrating an increase of nearly ten times at the national level. all fifty states witnessed an increase in the number of tweets exclusively mentioning chinese virus or china virus instead of covid-19 or coronavirus. on average, 0.38 tweets referencing chinese virus or china virus were posted per 10,000 population at the state level in the pre-period, and 4.08 of these stigmatizing tweets were posted in the post-period, also indicating a ten fold increase. the five states with highest number of post-period chinese virus tweets were pennsylvania 5,249, new york 11,754, florida 13,070, texas 14,861, and california 19,442. adjusting for population size, the five states with the highest prevalence of post-period chinese virus tweets were arizona 5.85, new york 6.04, florida 6.09, nevada 7.72, and wyoming 8.76. the five states with the largest increase in pre- to post-period chinese virus tweets were kansas 1,202%, south dakota 1,233%, mississippi 1,387%, new hampshire 1,420%, and idaho 1,457%. conclusions the rise in tweets referencing chinese virus or china virus, along with the content of these tweets, indicate that 1 knowledge translation may be occurring online and that 2 covid-19 stigma is likely being perpetuated on twitter. clinicaltrial"
  8  "background stigma is the deleterious, structural force that devalues members of groups that hold undesirable characteristics. since stigma is created and reinforced by society-through in-person and online social interactions-referencing the novel coronavirus as the chinese virus or china virus has the potential to create and perpetuate stigma. objective the aim of this study was to assess if there was an increase in the prevalence and frequency of the phrases chinese virus and china virus on twitter after the march 16, 2020, us presidential reference of this term. methods using the sysomos software sysomos, inc, we extracted tweets from the united states using a list of keywords that were derivatives of chinese virus. we compared tweets at the national and state levels posted between march 9 and march 15 preperiod with those posted between march 19 and march 25 postperiod. we used stata 16 statacorp for quantitative analysis, and python python software foundation to plot a state-level heat map. results a total of 16,535 chinese virus or china virus tweets were identified in the preperiod, and 177,327 tweets were identified in the postperiod, illustrating a nearly ten-fold increase at the national level. all 50 states witnessed an increase in the number of tweets exclusively mentioning chinese virus or china virus instead of coronavirus disease covid-19 or coronavirus. on average, 0.38 tweets referencing chinese virus or china virus were posted per 10,000 people at the state level in the preperiod, and 4.08 of these stigmatizing tweets were posted in the postperiod, also indicating a ten-fold increase. the 5 states with the highest number of postperiod chinese virus tweets were pennsylvania n5249, new york n11,754, florida n13,070, texas n14,861, and california n19,442. adjusting for population size, the 5 states with the highest prevalence of postperiod chinese virus tweets were arizona 5.85, new york 6.04, florida 6.09, nevada 7.72, and wyoming 8.76. the 5 states with the largest increase in pre- to postperiod chinese virus tweets were kansas n69758, 1202%, south dakota n18515, 1233%, mississippi n74954, 1387%, new hampshire n58241, 1420%, and idaho n67046, 1457%. conclusions the rise in tweets referencing chinese virus or china virus, along with the content of these tweets, indicate that knowledge translation may be occurring online and covid-19 stigma is likely being perpetuated on twitter."
  **9  "0.47"
 10  "0.69"**
 11  "1.0"
 12  "-1.0"
 13  "0.9323495"
 14  "0.0"
 15  "2020-09-24"

descrição dos campos:
mfn=     1
  **1  "Covidence1"
  2  "Covidence2"**
  3  "doi1"
  4  "doi2"
  5  "title1"
  6  "title2"
  7  "abstract1"
  8  "abstract2"
  **9  "Title_Similarity"
 10  "Abstract_Similarity"**
 11  "Authors_Jaro_Distance"
 12  "Author_Fuzz_Match"
 13  "Probability"
 14  "Prediction"
 15  "time_stamp"

Não é o caso de mexer nas regras, penso eu.

**Comment by renatomurasaki** [comment]
@botturam obrigado. Esse é um caso de falso negativo, pois deveria ser considerado duplicado mas não foi. O problema maior é que por ser um DOI encontrado em MEDLINE, ambos ficaram com o título identifico na interface de busca, pois tiveram os metadados enriquecidos

![image](https://user-images.githubusercontent.com/1226218/94839600-97921d80-03ed-11eb-9947-00286b479f42.png)

![image](https://user-images.githubusercontent.com/1226218/94839637-a1b41c00-03ed-11eb-925b-dae1b316461e.png)

O que você acha de implementar uma checagem direta de campos (PMID e DOI) na base final do processo, após ter passado pelo enriquecimento e deduplicação?

**Comment by botturam** [comment]
ótima ideia. Fiz uma conta e o resultado foi:

operacao@serverofi5:/bases/mdlG4/cov.mdl.2 $ mx mdl "pft=v969,v968/" lw=0 now|wc
  55663   55793 2563710
operacao@serverofi5:/bases/mdlG4/cov.mdl.2 $ mx mdl "pft=v969,v968/" lw=0 now|sort -u|wc
  51231   51355 2343787

tirando os repetidos (4.000 docs), sobram 51.000 docs de MEDLINE.

Estou implementando.

**Comment by renatomurasaki** [comment]
Isso significa que há 4000 repetidos, além daquilo que conseguimos identificar via parametros Elsevier?

**Comment by renatomurasaki** [comment]
Para esses documentos, você consegue garantir o funcionamento do alternate_id para retirar os duplicados?

**Comment by renatomurasaki** [comment]
Antigamente, qdo preservava o ID do medline, os repetidos era eliminados com o overwrite do XML do Lucene. Como mantivemos o refID, essa capacidade se perdeu

**Comment by renatomurasaki** [comment]
@botturam isso já foi implementado, correto?

**Comment by botturam** [comment]
sim. Já foi implemtentado.
