### ISSUE TITLE
Exportar lista de títulos de periódicos da base WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#462]
Enviar para o Garnica asap, por favor.

**Comment by botturam** [comment]
Enviado em:

Qui, 28/01/2021 17:17
Garnica,

attached are two new files:

1) covidwho_numberdocs_journalname_ISSN.xlsx
2) covidwho_numberdocsXjournalname.xlsx

the table covidwho_numberdocsXjournalname has more documents grouped than covidwho_numberdocs_journalname_ISSN because ISSN data is not completely normalized.
