### ISSUE TITLE
Qual é a explicação para a diferença na recuperação de documentos no GIM e Regional para a expressão TW contra TI OR AB OR MH

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#489]
tw:(vaccin* and covid*) and not (ti:(vaccin* and covid*) OR ab:(vaccin* and covid*) OR mh:(vaccin* and covid*))

Por que há documentos na recuperação do TW que não são recuperados na combinação de TI, AB e MH, se o TW é teoricamente a soma destes campos?

**Comment by renatomurasaki** [comment]
Outro exemplo na interface WHO COVID (que tem analizador diferente do Regional e GIM:

tw:covid - retorna 11.053

ti:covid OR ab:covid OR mh:covid - retorna 207.072

**Comment by renatomurasaki** [comment]
Relacionado com #490

**Comment by botturam** [comment]
Essa pesquisa não contempla a segunda parte (and not), pois tem **ti:covid** e **ab:vaccine**. A parte ti e ab dessa expressão (ti e ab; ignorar mh) não retornam resultado por causa do "and".

tw:(vaccin* and covid*) and not **(ti:(vaccin* and covid*) OR ab:(vaccin* and covid*)** OR mh:(vaccin* and covid*))

  <doc boost="45">
    <field name="id">covidwho-1243772</field>
    <field name="bvs">regional</field>
    <field name="db">Sage</field>
    <field name="instance">regional</field>
    <field name="collection">04-international_org</field>
    <field name="type">article</field>
    <field name="nivel_tratamento">as</field>
    <field name="ur">https://doi.org/10.1177/09544089211019581</field>
    <field name="au">Gok, Kadir</field>
    <field name="ti">Investigation of the use of silicone pads to reduce the effects on the human face of classical face masks used to prevent from **COVID**-19 and other infections</field>
    <field name="pg">09544089211019581</field>
    <field name="fo">Proceedings of the Institution of Mechanical Engineers, Part E: Journal of Process Mechanical Engineering;: 09544089211019581, 2021.</field>
    <field name="ta">Proceedings of the Institution of Mechanical Engineers, Part E: Journal of Process Mechanical Engineering</field>
    <field name="la">en</field>
    <field name="pu">Sage</field>
    <field name="dp">2021</field>
    <field name="da">202100</field>
    <field name="ab">Viruses spreads very quickly and has a fatal risk in people with chronic disease  As the virus **vaccine** and medications to be used for treatment are not fully developed, alternative ways to protect it from the virus are being investigated  In this study, the effects of a classical face mask on human face were investigated and computer-aided analyses were performed  Three-dimensional model of the classical face mask was performed with the SolidWorks software  The analyses were performed using AnsysWorkbench Static Structural module  The load, boundary conditions and material were defined in the AnsysWorkbench  As a result of the analyses, it has been determined that classical masks influence human face  The classical masks have a negative effective in terms of irritation on the human face  The occurred stresses cause irritation on one's skin  The use of silicone pads has been shown to reduce these effects  It was proved by this study that silicon pads can be used as an alternative method to reduce these stresses  In the future, it is planned to conduct studies investigating mask materials that do not irritate the human face</field>

**Comment by botturam** [comment]
A respeito da segunda estratégia de pesquisa  --  (ti:(covid*) or ab:(covid*) or mh:(covid*)) and not tw:(covid*)  --, notar que a diferença é bem grande:

covid-SoLR3:  https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/
7.778 docs

covid-SoLR5:  https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/
2 docs

Notei que a expressão (COVID-19), por exemplo, não gera chave no índice TW em SoLR3.

a pesquisa abaixo funciona em SoLR5, mas não em SoLR3: 
id:covidwho-1244976 and tw:(covid*)

\<field name="ab"\>Introduction Asthma is a clinical syndrome characterized by reversible and recurrent airway obstruction leading to the symptoms of wheezing, cough, shortness of breath, fatigue, and respiratory distress  It is one of the most common lung pathologies worldwide  Its incidence is on the rise in Pakistan, which may be due to overt environmental pollution or improving screening protocols  Irrespective more and more patients are now being diagnosed as cases of asthma and this has led to renewed interest in research for the subject locally  Vitamin D plays a key component of the immune system and its deficiency has been associated with diseases, such as inflammatory bowel disease, celiac disease, rheumatoid arthritis, depression, sepsis, and coronavirus disease 2019 (COVID-19) pneumonia

**Comment by renatomurasaki** [comment]
@viniciusandrade por favor, poderia documentar aqui os demais campos que o TW inclui, além de TI, AB e MH?

**Comment by viniciusandrade** [comment]
@renatomurasaki estes campos são definidos no **schema.xml** do índice e mantidos pelo OFI. 

Segue trecho referente ao tw copiados do arquivo da serverofi5:
```
 <copyField source="ti"               dest="tw" />
 <copyField source="ti_*"             dest="tw" />
<!--<copyField source="au"               dest="tw" />-->
 <copyField source="ab"               dest="tw" />
 <copyField source="ab_*"             dest="tw" />
 <copyField source="otherab"          dest="tw" />
 <copyField source="ct"               dest="tw" />
 <copyField source="pt"               dest="tw" />
 <copyField source="mj"               dest="tw" />
 <copyField source="mh"               dest="tw" />
 <copyField source="kw"               dest="tw" />
 <copyField source="nm"               dest="tw" />
<!-- copia sinomimos dos termos decs para tw -->
 <copyField source="decs_syn_*"       dest="tw" />
```

**Comment by botturam** [comment]
1) tw:covid - 11.053
2) ti:covid OR ab:covid OR mh:covid - 207.072

Essa expressão: ti:covid OR ab:covid OR mh:covid
Essa outra.........: ti:covid OR ab:covid

são equivalentes, pois não existe índice mh (ou mj) apenas com palavras. Entretanto, no TW, existem entradas do índice com palavras do Descritor. Não há que se comparar 1) x 2)
