### ISSUE TITLE
Teste de planilha Excel gerada a partir de MacOS

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#567]
@botturam , por favor, teste com o Excel do Windows a planilha em anexo enviada pela Deborah. Sugestão: exporte a mesma em csv e depois com o mx cheque os campos (principalmente as linhas 7 e 8). Com o meu LibreOffice as colunas não estavam corretas. Obrigado.

[who-repo4covid-biblio-TINI 23.7.xlsx](https://github.com/bireme/db-processing/files/6885667/who-repo4covid-biblio-TINI.23.7.xlsx)

**Comment by botturam** [comment]
@heitorbarbieri o arquivo está bem, legível e íntegro. Fiz exatamente o que vc indicou. 

Apenas a ressalva de que os caracteres árabes dos recs 7 e 8 não foram identificados.

mfn=     7
  1  "1317459"
  2  "????, ???????, ??? ???????, ????, ????, ????????, ????? ?????, ????"
  3  "Clinical Features and Paraclinical Findings of Patients Died of COVID-19 in a Referral Hospital in Sari, Iran, February 2020-May 2020."
  4  "Background and purpose: The Coronavirus Disease 2019 (COVID-19) was first observed in December 2019 and caused a global pandemic. The aim of this study was to evaluate the clinical features and paraclinical findings in patients who died of COVID-19 in Sari Imam Khomeini Hospital, February 2020- May 2020. Materials and methods: A cross-sectional descriptive and retrospective study was done by reviewing the medical records of 149 patients who died of Covid-19 whose diagnosis was confirmed by chest CT scan or PCR-RT. Independent sample t test was used to compare quantitative variables and Chisquare test was used for analyzing qualitative variables. Results: The mean age of death from Covid-19 was 63.36▒15.26 years and 58.1% were male. The most common clinical complaints were cough, fever, and dyspnea. The most common manifestation of chest CT scan was bilateral involvement. Among the dead cases of COVID-19, 13.5% had myocarditis and 4.7% developed respiratory complications (such as pneumothorax). According to findings, 54.1% died of cardiac arrest and 44.6% died due to respiratory arrest. Conclusion: Many ambiguities of SARS-CoV-2 still remain that require extensive studies and research in various aspects. Evaluation of demographic, radiological, clinical complications, and laboratory features can help physicians in finding ways to reduce mortality, perform more effective treatments, and use predictive tools. [ABSTRACT FROM AUTHOR] Copyright of Journal of Mazandaran University of Medical Sciences (JMUMS) is the property of Mazandaran University of Medical Sciences and its content may not be copied or emailed to multiple sites or posted to a listserv without the copyright holder's express written permission. However, users may print, download, or email articles for individual use. This abstract may be abridged. No warranty is given about the accuracy of the copy. Users should refer to the original published version of the material for the full abstract. (Copyright applies to all Abstracts.)"
  8  "23-07-21"
  9  "Academic Search Complete"
 13  "198"
 14  "Journal of Mazandaran University of Medical Sciences"
 15  "fa"
 17  "119-132"
 22  "????? ??????? ?????? ? ????? ??? ?????????? ?? ??????? ????? ?? ?????- 91?? ????????? ???? ????? ???? ?? ???? ????? ????? 9911 ?? ????? ???????? 9911"
 23  "JOUR"
 24  "31"
 25  "2021"
..
mfn=     8
  1  "1317460"
  2  "??????? ?????, ??, ????? ??????, ???, ??? ???????, ????, ??? ?????, ??????, ???? ????, ?????, ?????, ?????, ?????, ??????, ????, ????????"
  3  "Relationship between Spiritual Health and the Effects of Grief in Bereaved Survivors of COVID-19 in Mashhad, Iran 2020."
  4  "Background and purpose: Coronavirus 2019 (COVID-19) is an infectious disease with a death rate of 1-5%. The aim of this study was to determine the relationship between spiritual health and the effects of grief from the loss of loved one due to COVID-19. Materials and methods: This cross-sectional study was performed in 312 family members of the deceased COVID-19 patients in Mashhad, Iran, April-September 2020. Non-randomized sampling was performed and data were collected online using the Grief Experience Questionnaire (GEQ-34) and the Spiritual Well Being Scale. Data were analyzed using descriptive tests and Pearson correlation coefficient. Results: According to findings, the highest score in dimensions of grief experience was found for the dimension of stigma (3.89▒0.54), followed by the attempt to justify and cope with the absence of the deceased person (3.49▒0.43), and judgment of the person or others about the cause of death (3.23▒0.37). The highest relationship between spiritual health and reducing the effects of grief was seen in the dimensions of embarrassment and shame (r= -0.593), guilt (r= -0.566), and abandonment (r= -0.535). Conclusion: Abnormal grief in the family of deceased COVID-19 patients is common which could have a negative impact on physical, mental, social, and functional health. So, social support and strengthening spiritual health are needed to reduce the effects of grief in bereaved survivors. [ABSTRACT FROM AUTHOR] Copyright of Journal of Mazandaran University of Medical Sciences (JMUMS) is the property of Mazandaran University of Medical Sciences and its content may not be copied or emailed to multiple sites or posted to a listserv without the copyright holder's express written permission. However, users may print, download, or email articles for individual use. This abstract may be abridged. No warranty is given about the accuracy of the copy. Users should refer to the original published version of the material for the full abstract. (Copyright applies to all Abstracts.)"
  8  "23-07-21"
  9  "Academic Search Complete"
 13  "198"
 14  "Journal of Mazandaran University of Medical Sciences"
 15  "fa"
 17  "109-118"
 22  "?????? ???????? ????? ? ????? ??? ?? ??????? ??????? ???? ?? ?????-19????? ????-2020"
 23  "JOUR"
 24  "31"
 25  "2021"

**Comment by botturam** [comment]
@heitorbarbieri  posso encerrar esse chamado?

**Comment by heitorbarbieri** [comment]
Pode.
